---
title: "EBM Nature Communications main script"
author: "Kirstin Holsman"
date: "2/17/2020"
output:
  pdf_document:
    fig_caption: yes
    highlight: tango
    keep_tex: yes
    latex_engine: xelatex
  html_document:
    df_print: kable
    fig_caption: yes
    theme: flatly
  header-includes:
  - \usepackage{inputenc}
  - \usepackage{unicode-math}
  - \pagenumbering{gobble}

  word_document:
    fig_caption: yes
    fig_width: 4
    keep_md: yes
---



# Data and code are under review and subject to change. Do not use without permission from lead author: kirstin.holsman@noaa.gov

#### Kirstin Holsman
#### kirstin.holsman@noaa.gov
#### Alaska Fisheries Science Center, National Marine Fisheries Service, NOAA, 7600 Sand Point Way N.E., Bld. 4, Seattle, Washington 98115

---

Code used to generate intermediate and final data for Holsman et al. in review Nature Communications paper

## Input data:

### Option 1: Re-generate final data for plots
If running plotting code below (recommended) you will need to download the final data "EBM_ceattlenew.Rdata" from figshare and place it in the main directory: "EBM_Holsman_NatComm/EBM_ceattlenew.Rdata".

* access EBM_ceattlenew.Rdata here: https://figshare.com/s/6dea7722df39e07d79f0 and place it in the directory: EBM_Holsman_NatComm/EBM_ceattlenew.Rdata. 
(Data DOI:10.6084/m9.figshare.11864505)

### Option 2: Re-running the intermediate data (not recommended)
If re-running the intermediate data analysis (not recommended) the following files will need to be downloaded unzipped and placed in the asssesment_files folder:

* access aclim_00_JunV2_2019_2.zip here: https://figshare.com/s/3a1aaa86837b79d6aa07 and place it in the EBM_Holsman_NatComm/data/runs/aclim_00_JunV2_2019_2.zip and unzip.
(Data DOI:10.6084/m9.figshare.11864586)

* access aclim_00_JunV2_2019_0.zip here: https://figshare.com/s/d9c35dbe0880f4169041 and place it in the EBM_Holsman_NatComm/data/runs/aclim_00_JunV2_2019_0.zip and unzip
(Data DOI:10.6084/m9.figshare.11864577)


## Intermediate data:
Intermediate data can be found in the main EBM_Holsman_NatComm in the form of .Rdata files but can be recreated (although this is not recommended; see below) from the ADMB model using the EBM_Holsman_NatComm/assessment_scripts/README_EBM_Holsman_Analysis.pdf.

## Figures and tables:
Final figures and tables (including illustrator files that were used to add fish icons) can be found in the **Figures** folder.


This is the main script for running analysis and plotting results and requires R version 3.5.3 (available at https://cran.r-project.org/bin/macosx/el-capitan/base/). To update the analysis using .Rdata outputs run the R() code below as is currently configured. If you want to update the intermediate data, set "readdat" to TRUE in line 80 below. The CEATTLE stock assessment is also included but requires AD Model builder (http://www.admb-project.org). To run the assessment scripts (not recommended or tested outside of macOSX) see "README_EBM_Holsman_Analysis.pdf".

### EMB_paper.R script:

```{r EBM_paper, eval=FALSE, echo=TRUE}

## ------------------------------------------------
## plotting code for EBM paper 
## Kirstin Holsman 
## Feb 2020
## Kirstin.holsman@noaa.gov
## ------------------------------------------------

# 1. Set up
# 2. load data
# 3.  make figures


    rm(list=ls())
    graphics.off()
    
  #-------------------------------------
  #   1. SET THINGS UP
  #-------------------------------------  
   # library(RmarineHeatWaves)
   # library(plyr)
    if(!require(dplyr)){ install.packages(dplyr)}else{library(dplyr)}
    if(!require(ggplot2)){ install.packages(ggplot2)}else{library(ggplot2)}
    if(!require(svMisc)){ install.packages(svMisc)}else{library(svMisc)}
    if(!require(quantmod)){ install.packages(quantmod)}else{library(quantmod)}
    
    main  <-  path.expand("~/GitHub_new/EBM_Holsman_NatComm/")
    setwd(main)
   
    update.figs     <-  FALSE
    fldr            <-  "aclim_00_JunV2_2019"  # folder with the CEATTLE assessment runs
    UpdateMCMC      <-  1      # update MCMC?
    readdat         <-  FALSE  # re-read in new data?
    status          <-  TRUE   # print updates
    dpiIN           <-  150
    update.simlist  <-  FALSE  # only TRUE when re-running enitre CEATTLE fitting 
    
    
    getnm<-function(nm=mclist0[1]){
      nmi<-strsplit(nm,split=paste0("Summary_proj_",fldr))[[1]][2]
      nmi<-strsplit(nmi,split="_mc")[[1]][1]
      return(paste0("dat",nmi,"_mc"))

    }

    
  #-------------------------------------
  #   2. LOAD DATA
  #-------------------------------------      

    source("FUN_GG_EBM_paper.R")
    source("FUN_EBM_paper.R")
    
    if(readdat==FALSE){
      if(!any(dir()%in%"EBM_ceattlenew.Rdata"))
        stop("EBM_ceattlenew.Rdata file not found, please go to 
          https://figshare.com/s/6dea7722df39e07d79f0 
          and download file into EBM_Holsman_NatComm/EBM_ceattlenew.Rdata")
        #download.file("https://figshare.com/s/6dea7722df39e07d79f0",destfile="EBM_ceattlenew.Rdata")
      load("EBM_ceattlenew.Rdata")    
    }else{
        source("SUB_EBM_paper.R")
        save.image(file = "EBM_ceattlenew.Rdata")
    } 
    

    riskTypes       <-  c("10% decline","50% decline","80% decline")
    RISK            <-  list("no cap" = risk12,"2 MT cap" = risk13)
    timeF           <-  levels(risk12$timeframe)


    flList          <-  dir("data/runs",paste0(fldr,"_0"))
    txt             <-  c("no cap"="_219_CENaivecf_2_5_12","2MT cap"="_2MT_219_CENaivecf1_2_5_13")
    fldin           <-  (paste0("data/runs/",fldr,"_2/projections/",fldr,txt,"/",fldr,txt,".ctl")) # KEY RUN
    target_B_2      <-  rbind(
                          getBtarget(fldrIN=fldin[1],nm="B0_set"),
                          getBtarget(fldrIN=fldin[2],nm="B0_set"))
    rownames(target_B_2)  <-  names(txt)
    txt              <-  c("no cap"="_019_CENaivecf_0_5_12","2MT cap"="_2MT_019_CENaivecf1_0_5_13")
    fldin            <-  (paste0("data/runs/",fldr,"_0/projections/",fldr,txt,"/",fldr,txt,".ctl")) # KEY RUN
    target_B_0       <-  rbind(
                          getBtarget(fldrIN=fldin[1],nm="B0_set"),
                          getBtarget(fldrIN=fldin[2],nm="B0_set"))
    rownames(target_B_0)<-names(txt)


# set the color scheme
    coll_use         <-  c(colors()[320],col2(6)[c(2,3,4)],col3(6)[c(3,4,6)])
    
# set up some plotting labels
    A1B_n_sim           <-  grep("A1B",simnames)
    bio_n_sim           <-  grep("bio",simnames)
    rcp45_n_sim         <-  grep("rcp45",simnames)
    rcp85_n_sim         <-  grep("rcp85",simnames)
    rcp85NoBio_n_sim    <-  setdiff(rcp85_n_sim,bio_n_sim)
    meanhistT           <-  mean(TempC_219_CENaivecf_2_5_12_mc[s,,,1][1,][hind_yrs])
      
    # get target biomass from ctl files:
    cumlyr  <-  function(x,sumyr=3){
      
      x<-as.numeric(x)
      x2<-x*0
      for(i in sumyr:length(x)){
        x2[i]<-ifelse(sum(x[i-(1:sumyr)+1])==sumyr,1,0)
      }
      return(x2==1)

    }

# plot cumulative years above threshold:
    plot_figS6<-function(){
      dev.new(height=3.25*1.3,width=4.5*1.3)
      head(TempC_019_CENaivecf_0_5_3_mc[1,1,,])
      above         <-  TempC_019_CENaivecf_0_5_3_mc[1,1,,]>2.16
      tt1           <-  apply(above,2,cumlyr,sumyr=5)
      tt            <-  apply(tt1,2,cumsum)/length(above[,1])
      yrs2          <-  as.numeric(rownames(above))
      findthrsh     <-  function(x,thrsh=.25,yrsIN=yrs2){
        yrsIN[as.numeric(x)>thrsh][1]
      }
      
      yrt           <-  apply(tt,2,findthrsh)
      plot(yrs2,tt)
      yrt[rcp85NoBio_n-1]
      yrt[rcp45_n-1]
      nscen         <-  length(c(rcp45_n,rcp85NoBio_n))
      plot(yrs2,tt[,2],ylim=c(0,nscen*1.2),xlim=c(1965,2100),type="l",col=NA,axes=F,ylab="",xlab="")
      axis(1)
      firstY<-rep(2017,nscen);names(firstY)<-colnames(tt1)[c(rcp45_n,rcp85NoBio_n)-1]
      
      for(i in 1:nscen){
        cc              <-  (c(rcp45_n,rcp85NoBio_n)-1)[i]
        ll              <-  NA*tt1[,cc]
        ll[tt1[,cc]]    <-  i
        suby            <-  yrs2[tt1[,cc]]
        if(any(suby>2017))
          firstY[i]    <-  suby[suby>2017][1]
        points(yrs2,ll,pch=16,cex=1.5,col=makeTransparent((wes(6))[i],alpha=250))
    }
    
    text(rep(1980,nscen),1:nscen,colnames(tt1)[c(rcp45_n,rcp85NoBio_n)-1],cex=.8,col=(wes(6))[1:nscen])
    mean(firstY[1:3],na.rm=T)
    mean(firstY[4:6],na.rm=T)
    }
    

#-------------------------------------
# 3. Final figures:
#-------------------------------------
#fig 2: temperature
   graphics.off()
      GGplot_aclimTS(dat=allDat,h=2*1.3,w=4.75*1.3,
        ylabb=expression(paste("Bottom temperature",'('^{o},"C)")),
        ltyy=c("solid",rep("solid",6)),
        subtitle_face="plain",
        plotSet=list(c(1,rcp45_n),c(1,rcp85NoBio_n)),
        coll=coll_use,tline=2,talpha=.5,
        xlabb="",lgnpos= "right",plot_marginIN=c(-10,-1,-10,1))

   if(update.figs) ggsave(file=paste0("Figures/Fig2.tiff"), device = "tiff", 
      scale = 1, width = NA, height = NA, units = "in",
      dpi = dpiIN)  
      
#fig X suppl zoop: temperature
   graphics.off()
      GGplot_aclimTS(dat=allDat,h=2*1.3,w=4.75*1.3,
                     fn="BT",
        ylabb=expression(paste("Bottom temperature",'('^{o},"C)")),
        ltyy=c("solid",rep("solid",6)),
        subtitle_face="plain",
        plotSet=list(c(1,rcp45_n),c(1,rcp85NoBio_n)),
        coll=coll_use,tline=2,talpha=.5,
        xlabb="",lgnpos= "right",plot_marginIN=c(-10,-1,-10,1))

   if(update.figs) ggsave(file=paste0("Figures/Figsupp_zoop.tiff"), device = "tiff", 
      scale = 1, width = NA, height = NA, units = "in",
      dpi = dpiIN)  

#fig 3: delta B
    # 50% quantiles
  graphics.off()
      GGplot_aclimCEATTLE_delta(h=4.75*1.3,w=4.75*1.3,
        nmLIST  = list("SSB0"="dat_219_CENaivecf_2_5_12","SSB0"="dat_219_CENaivecf_2_5_12"),
        datLIST = list(dat1=B0_219_CENaivecf_2_5_12_mc,dat2=B0_219_CENaivecf_2_5_12_mc),
        valLIST = list(valIn1="SSB0_total_biom", valIn2="SSB0_total_biom"),
        prob= c(.01,.50,.9),plot_marginIN=c(-15,5,-10,5),alpha=c(10,5),lgnpos= "bottom",coll=coll_use)

  if(update.figs) ggsave(file=paste0("Figures/Fig3.tiff"), device = "tiff", 
      scale = 1, width = NA, height = NA, units = "in",
      dpi = dpiIN)

#fig 4: delta C
    # 50% quantiles
 

  graphics.off()
      GGplot_aclimCEATTLE_delta(deltaIN=TRUE,h=4.75*1.3,w=4.75*1.3,ydiv=1,
        ylimm_up=c(100,100,100),ylimm_dwn=c(-200,-200,-200),
        plot_marginIN=c(-15,5,-10,5),alpha=c(0,0),lwdd=c(.7,.3),plotpersist = FALSE,
        coll = coll_use,
        ylabb   = expression(paste(Delta," Catch (%)")),
        xlimmIN = c(2010,2100),
        nmLIST  = list("2 MT cap"="dat_2MT_219_CENaivecf1_2_5_13","no cap"="dat_219_CENaivecf_2_5_12"),
        valLIST = list(valIn1="Catch_total_biom", valIn2="Catch_total_biom"),
        datLIST = list(dat1=B_219_CENaivecf_2_5_12_mc,dat2=B_219_CENaivecf_2_5_12_mc),
        lgnpos= "bottom",scalesIN="fixed")


  if(update.figs) ggsave(file=paste0("Figures/Fig4.tiff"), device = "tiff", 
      scale = 1, width = NA, height = NA, units = "in",
      dpi = dpiIN)

  #fig 5: risk
  graphics.off()
      GGplot_aclimCEATTLE_risk(h=2*1.3,w=4*1.3,coll= c(col2(6)),sp=1,colvar="type",rowvar="sp",alpha=c(.4,1),
        plot_marginIN=c(-15,0,-10,5),mode="MSM",lwdd=c(.7,.4,.4),rcpIN=c("RCP 8.5"="rcp85"),
        nrowlg  = c(1,1),pchh=c(16,15),
        lgnpos= "bottom",RISKTYPES = riskTypes[c(1,2,3)],ltyy=c("solid","solid","solid"))

        grid.force()
        # change shape of arrows
        grid.gedit("segments", gp=gpar(linejoin ='mitre'))
        # change the shape in legend also
        grid.gedit("layout", gp=gpar(linejoin ='mitre'))

  if(update.figs) ggsave(file=paste0("Figures/Fig5.tiff"), device = "tiff", 
      scale = 1, width = NA, height = NA, units = "in",
      dpi = dpiIN)


  #fig 6: Threshold

dev.new(height=4.75*1.3,width=4.5*1.3)
PLOT_THRESHOLD2(
  multIN=10,
  firstdiff=T,
  ntemps=3,
  ylimmIN =c(-1,1.5),
  xlimmIN =c(1,7),
  trndln  = "white",
  trndln2 = Ornjazz[3],
  tipping = Ornjazz[5],
  sizeIN=c(0.1,.3,.75,2))

 if(update.figs) ggsave(file=paste0("Figures/Fig6.tiff"), device = "tiff", 
      scale = 1, width = NA, height = NA, units = "in",
      dpi = dpiIN)

# Fig S1: HCR


  graphics.off()
  GG_HCRplot(h=3.5,w=8,futScen="GFDL_rcp45",fontSize=3,yfont=c(2070,2073))


 if(update.figs) ggsave(file=paste0("Figures/FigS1.tiff"), device = "tiff", 
      scale = 1, width = NA, height = NA, units = "in",
      dpi = dpiIN)

# Fig S2: SSB with and without cap


      GGplot_aclimCEATTLE_delta(deltaIN=F,h=4.75*1.3,w=4.75*1.3,ydiv=1e6,
        plot_marginIN=c(-15,5,-10,5),alpha=c(0,0),lwdd=c(.7,.3),
        ylabb   = "Spawning biomass (million tons)",
        nmLIST  = list("2 MT cap"="dat_2MT_219_CENaivecf1_2_5_13","no cap"="dat_219_CENaivecf_2_5_12"),
        valLIST = list(valIn1="SSB_total_biom", valIn2="SSB_total_biom"),
        datLIST = list(dat1=B_219_CENaivecf_2_5_12_mc,dat2=B_219_CENaivecf_2_5_12_mc),
        lgnpos= "bottom",scalesIN="free_y")
  if(update.figs) ggsave(file=paste0("Figures/FigS2.tiff"), device = "tiff", 
      scale = 1, width = NA, height = NA, units = "in",
      dpi = dpiIN)

# Fig S3: effective F


  graphics.off()
  dev.new(height=3.5,weight=5)
  plot_Feffective()

 if(update.figs) ggsave(file=paste0("Figures/FigS3.tiff"), device = "tiff", 
      scale = 1, width = NA, height = NA, units = "in",
      dpi = dpiIN)



# Fig S4: risk plot
 
    graphics.off()
      GGplot_aclimCEATTLE_risk(h=4.75*1.3,w=3.2*1.3,coll= c(col2(6)),colvar="type",rowvar="sp",alpha=c(.4,1),
        plot_marginIN=c(-15,5,-10,5),mode="MSM",lwdd=c(.7,.4,.4),rcpIN=c("RCP 8.5"="rcp85"),pchh=c(16,15),
        lgnpos= "bottom",RISKTYPES = riskTypes[c(1,3)],ltyy=c("solid","solid"))

        grid.force()
        # change shape of arrows
        grid.gedit("segments", gp=gpar(linejoin ='mitre'))
        # change the shape in legend also
        grid.gedit("layout", gp=gpar(linejoin ='mitre'))

if(update.figs) ggsave(file=paste0("Figures/FigS4.tiff"), device = "tiff", 
      scale = 1, width = NA, height = NA, units = "in",
      dpi = dpiIN)


# Fig S5: threshold 1
graphics.off()
dev.new(height=3*1.3,width=4.75*1.3)

PLOT_THRESHOLD(
  dataIN_1=tmpall12_1,
  dataIN_2=tmpall12_2,
  dataIN_3=tmpall12_3,
  firstdiff=F,
  ntemps=3,
  multIN=10,
  #ylimmIN =c(-1.5,1.5),
  #xlimmIN =c(.5,7),
  ylimmIN =c(-1,1.5),
  xlimmIN =c(1,7),
  trndln  = "white",
  trndln2 = Ornjazz[3],
  tipping = Ornjazz[5],
  sizeIN=c(0.1,.3,.75,2))


 if(update.figs) ggsave(file=paste0("Figures/FigS5.tiff"), device = "tiff", 
      scale = 1, width = NA, height = NA, units = "in",
      dpi = dpiIN)

# Fig S6: hindcast years
plot_figS6()
if(update.figs) quartz.save(file=paste0("Figures/Figs6_delta.pdf"), type = "pdf", 
                            width = 4.5*1.3, height = 3.25*1.3,dpi = dpiIN)  



```
