---
title: "table_for EBMpaper"
author: "Kirstin Holsman"
date: "12/10/2019"
output:
  html_document: default
  mainfont: Times New Roman
  pdf_document: default
  word_document: default
header-includes: \usepackage{fontspec}
always_allow_html: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(knitr)
library(kableExtra)


```

## R Markdown
## using the Arial font as an example
\fontspec{Times New Roman}

Table 1. 
```{r cars}
# write.csv(tmpOUT,file="RiskValue.csv")
# if(!require("expss")) install.packages("expss") 
# if(!require("kableExtra")) install.packages("kableExtra") 
# library(expss)
# library(kableExtra)
library(reshape)
library(dplyr)
load(file="/Users/kholsman/Documents/D_AFSC_Files/Manuscripts/00_EBM_ACLIM_CEATTLE/EBM_paper/tmpOUT.Rdata")


tabledat<-as_tibble(tmpOUT)%>%
  group_by(sp,timeF,rcp,noCapRC,noCapRCsd, CapRC, CapRCsd,deltaRC)
  
tabledat$NoCapC<-paste0(round(tabledat$noCapRC,1)," (",round(tabledat$noCapRCsd,1),")")
tabledat$CapC<-paste0(round(tabledat$CapRC,1)," (",round(tabledat$CapRCsd,1),")")

tabledat<-tabledat%>%
  group_by(sp,timeF,rcp,type,NoCapC,CapC,deltaRC)%>%
  select(sp,timeF,rcp,type,NoCapC,CapC,deltaRC)
tabledat$type<-substr(tabledat$type,1,3)

tabledat$deltaRC<-as.character(round(tabledat$deltaRC,1))

tbl_dat_long<-melt(data.frame(tabledat), id=c("sp", "timeF","rcp","type"))

first<-function(x,char=T) if(char) as.character(x[1]) else x[1]
tbl_dat<-cast(tbl_dat_long, rcp+sp + timeF ~ type+variable, first, margins="treatment")

kable(tbl_dat[,-(1:2)], caption = "Table 1") %>%
  kable_styling(full_width = F,font=10) %>%
  #collapse_rows(columns = 1:2, valign = "top")%>%
  pack_rows("a) RCP 4.5", 1, 12) %>%
  pack_rows("b) RCP 8.5", 13, 24) %>%
  pack_rows("walleye pollock", 1, 4) %>%
  pack_rows("Pacific cod", 5, 8) %>%
  pack_rows("arrowtooth flounder", 9, 12)%>%
  pack_rows("walleye pollock", 13, 16) %>%
  pack_rows("Pacific cod", 17, 20) %>%
  pack_rows("arrowtooth flounder", 21, 24)


```


##Templates

```{r cars2, eval=F,echo=F}
dt <- mtcars[1:5, 1:6]

kable(mtcars[1:10, 1:5]) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"),fixed_thead = T)


# NOW  narrow version
kable(dt) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)
# write.csv(tmpOUT,file="RiskValue.csv")
# if(!require("expss")) install.packages("expss") 
# if(!require("kableExtra")) install.packages("kableExtra") 
# library(expss)
# library(kableExtra)

# Best table for paper
kable(mtcars[1:10, 1:6], caption = "Group Rows") %>%
  kable_styling("striped", full_width = F) %>%
  pack_rows("Group 1", 4, 7) %>%
  pack_rows("Group 2", 8, 10) %>%
  footnote(general = "Here is a general comments of the table. ",
           number = c("Footnote 1; ", "Footnote 2; "),
           alphabet = c("Footnote A; ", "Footnote B; "),
           symbol = c("Footnote Symbol 1; ", "Footnote Symbol 2"),
           general_title = "General: ", number_title = "Type I: ",
           alphabet_title = "Type II: ", symbol_title = "Type III: ",
           footnote_as_chunk = T, title_format = c("italic", "underline")
           )



```
# Table 2: pretty in HTML but no good for word or pdf.
```{r Table2, eval=F,echo=F}
library(expss)


mtcars %>% 
  tab_cells(mpg, disp, hp, wt, qsec) %>%
  tab_cols(total(), am) %>% 
  tab_stat_mean_sd_n() %>%
  tab_last_sig_means(subtable_marks = "both") %>% 
  tab_pivot() %>% 
  set_caption("Table with summary statistics and significance marks.")

# Table with the same summary statistics. Statistics labels in columns.
tt<-mtcars %>% 
  tab_cells(mpg, disp, hp, wt, qsec) %>%
  tab_cols(total(label = "#Total| |"), am) %>% 
  tab_stat_fun(Mean = w_mean, "Std. dev." = w_sd, "Valid N" = w_n, method = list) %>%
  tab_pivot()

```


# Doesn't copy well:

```{r Table3, eval=F,echo=F}
dt <- mtcars[1:5, 1:4]
# HTML table
kable(dt, format = "html", caption = "Demo Table") %>%
  kable_styling(bootstrap_options = "striped",
                full_width = F) %>%
  add_header_above(c(" ", "Group 1" = 2, "Group 2[note]" = 2)) %>%
  add_footnote(c("table footnote"))


dt <- mtcars[1:5, 1:6]
kable(dt) %>%
  kable_styling(c("striped", "bordered")) %>%
  add_header_above(c(" ", "Group 1" = 2, "Group 2" = 2, "Group 3" = 2)) %>%
  add_header_above(c(" ", "Group 4" = 4, "Group 5" = 2)) %>%
  add_header_above(c(" ", "Group 6" = 6))


# add_header_above(c(" ", "Risk of 10% decline in catch" = 3, "Risk of 50% decline in catch" = 3,"Risk of 80% decline in catch" = 3)) %>%
# add_header_above(c(" ", "Decline" = 3,"Severe decline" = 3,"Collapse" = 3))

kirheader<-list(
  c(" ", "Risk of 10% decline in catch" = 2, "Risk of 50% decline in catch" = 2, "Risk of 80% decline in catch" = 2),
  c(" ", "Decline" = 2,"Severe decline" = 2,"Collapse" = 2))

# # HTML table
 kable(dt, format = "html", caption = "Demo Table") %>%
   kable_styling(bootstrap_options = "striped",full_width = F) %>%
   add_header_above(kirheader[[1]]) %>%
   add_header_above(kirheader[[2]])



kable(dt) %>%
  kable_styling("striped", full_width = F, font_size = 10) %>%
  add_indent(c(1, 3, 5))


collapse_rows_dt <- data.frame(C1 = c(rep("a", 10), rep("b", 5)),
                 C2 = c(rep("c", 7), rep("d", 3), rep("c", 2), rep("d", 3)),
                 C3 = 1:15,
                 C4 = sample(c(0,1), 15, replace = TRUE))
kable(collapse_rows_dt, align = "c") %>%
  kable_styling(full_width = F) %>%
  column_spec(1, bold = T) %>%
  collapse_rows(columns = 1:2, valign = "top")

```
